name: _error
timestamp: 1571022858
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1571022858
positions:
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-6778: Logo
  spacer:
    spacer-1665: Spacer
    spacer-8503: Spacer
  menu:
    menu-3531: Menu
  content:
    system-content-4147: 'Page Content'
  position:
    position-footer: Footer
  copyright:
    copyright-2912: Copyright
  branding:
    branding-4389: Branding
  mobile-menu:
    mobile-menu-9265: Mobile-menu
inherit: {  }
