name: _offline
timestamp: 1571022858
version: 7
preset:
  image: 'gantry-admin://images/layouts/offline.png'
  name: _offline
  timestamp: 1571022858
positions:
  footer: Footer
sections:
  header: Header
  main: Main
  footer: Footer
particles:
  logo:
    logo-1393: Logo
  spacer:
    spacer-9404: Spacer
    spacer-7485: Spacer
  messages:
    system-messages-4769: 'System Messages'
  content:
    system-content-9014: 'Page Content'
  position:
    position-footer: Footer
  copyright:
    copyright-9369: Copyright
  branding:
    branding-5966: Branding
inherit: {  }
