name: '13'
timestamp: 1571022143
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1571022142
positions:
  aside: Aside
  sidebar: Sidebar
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-7972: 'System Messages'
    system-messages-6601: 'System Messages'
  logo:
    logo-9608: 'Logo / Image'
    logo-9571: 'Logo / Image'
    logo-7037: 'Logo / Image'
    logo-5172: 'Logo / Image'
  menu:
    menu-6409: Menu
    menu-2248: Menu
  social:
    social-3171: Social
    social-4679: Social
  position:
    position-position-4734: Aside
    position-position-3949: Sidebar
    position-position-7033: Aside
    position-position-7026: Sidebar
  content:
    system-content-1587: 'Page Content'
    system-content-8360: 'Page Content'
  copyright:
    copyright-1736: Copyright
    copyright-2823: Copyright
  horizontalmenu:
    horizontalmenu-9034: 'Horizontal Menu'
    horizontalmenu-9339: 'Horizontal Menu'
  totop:
    totop-8670: 'To Top'
    totop-8216: 'To Top'
  mobile-menu:
    mobile-menu-5697: Mobile-menu
    mobile-menu-8393: Mobile-menu
inherit:
  default:
    navigation: navigation
    system-messages-7972: system-messages-7972
    logo-9608: logo-9608
    menu-6409: menu-6409
    social-3171: social-3171
    header: header
    intro: intro
    features: features
    utility: utility
    above: above
    testimonials: testimonials
    expanded: expanded
    aside: aside
    position-position-4734: position-position-4734
    mainbar: mainbar
    system-content-1587: system-content-1587
    sidebar: sidebar
    position-position-3949: position-position-3949
    footer: footer
    logo-9571: logo-9571
    copyright-1736: copyright-1736
    horizontalmenu-9034: horizontalmenu-9034
    totop-8670: totop-8670
    offcanvas: offcanvas
    mobile-menu-5697: mobile-menu-5697
    system-messages-6601: system-messages-7972
    logo-7037: logo-9608
    menu-2248: menu-6409
    social-4679: social-3171
    position-position-7033: position-position-4734
    system-content-8360: system-content-1587
    position-position-7026: position-position-3949
    logo-5172: logo-9571
    copyright-2823: copyright-1736
    horizontalmenu-9339: horizontalmenu-9034
    totop-8216: totop-8670
    mobile-menu-8393: mobile-menu-5697
